Repository DP2-IIS-C1048/Acme-ANS-D, pull requests merged in 2025-04, with the labels that each got.

#191 Added Sample Data
  src/main/resources/WEB-INF/data/sample/assistance-agent.csv
  src/main/resources/WEB-INF/data/sample/claim.csv
  src/main/resources/WEB-INF/data/sample/trackinglog.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: Student 4, D02, Mandatory

#186 Validado al 100% TrackingLog
  reports/Student#4/~$ - Requirements - Student #4.docx
  src/main/java/acme/constraints/TrackingLogValidator.java
  src/main/java/acme/constraints/ValidTrackingLog.java
  src/main/java/acme/entities/tracking_log/TrackingLog.java
  src/main/java/acme/entities/tracking_log/TrackingLogIndicator.java
Labels: Student 4, D02, Mandatory

#141 feat(AssitanceAgent): Añadidos los min y max a todos los atributos que se puede
  .classpath
  .project
  .settings/org.eclipse.wst.common.component
  src/main/java/acme/constraints/AssistanceAgentValidator.java
  src/main/java/acme/realms/assistanceagent/AssistanceAgent.java
Labels: Student 4, D02, Mandatory

#199 Añadidios datos iniciales de adminstrator
  src/main/resources/WEB-INF/data/initial/administrator.csv
  src/main/resources/WEB-INF/data/initial/user-account.csv
Labels: D02, Mandatory, Groupal

#202 Student2 m09
  .classpath
  .vscode/settings.json
  src/main/java/acme/entities/passenger/Passenger.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerController.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerCreateService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerListService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerPublishService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerRepository.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerShowService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerUpdateService.java
  src/main/resources/WEB-INF/data/sample/passenger.csv
  src/main/resources/WEB-INF/views/customer/passenger/form.jsp
  src/main/resources/WEB-INF/views/customer/passenger/list.jsp
  src/main/resources/WEB-INF/views/customer/passenger/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/passenger/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: Student 2, D03, Mandatory

#197 Student3 m8 & m9
  src/main/java/acme/entities/activity_log/ActivityLog.java
  src/main/java/acme/entities/flight_assignment/FlightAssignment.java
  src/main/java/acme/features/flight_crew_member/activity_log/FlightCrewMemberActivityLogController.java
  src/main/java/acme/features/flight_crew_member/activity_log/FlightCrewMemberActivityLogCreateService.java
  src/main/java/acme/features/flight_crew_member/activity_log/FlightCrewMemberActivityLogDeleteService.java
  src/main/java/acme/features/flight_crew_member/activity_log/FlightCrewMemberActivityLogListService.java
  src/main/java/acme/features/flight_crew_member/activity_log/FlightCrewMemberActivityLogPublishService.java
  src/main/java/acme/features/flight_crew_member/activity_log/FlightCrewMemberActivityLogRepository.java
  src/main/java/acme/features/flight_crew_member/activity_log/FlightCrewMemberActivityLogShowService.java
  src/main/java/acme/features/flight_crew_member/activity_log/FlightCrewMemberActivityLogUpdateService.java
  src/main/java/acme/features/flight_crew_member/flight_assignments/CompletedFlightAssignmentListService.java
  src/main/java/acme/features/flight_crew_member/flight_assignments/FlightCrewMemberFlightAssignmentController.java
  src/main/java/acme/features/flight_crew_member/flight_assignments/FlightCrewMemberFlightAssignmentCreateService.java
  src/main/java/acme/features/flight_crew_member/flight_assignments/FlightCrewMemberFlightAssignmentDeleteService.java
  src/main/java/acme/features/flight_crew_member/flight_assignments/FlightCrewMemberFlightAssignmentPublishService.java
  src/main/java/acme/features/flight_crew_member/flight_assignments/FlightCrewMemberFlightAssignmentRepository.java
  src/main/java/acme/features/flight_crew_member/flight_assignments/FlightCrewMemberFlightAssignmentShowService.java
  src/main/java/acme/features/flight_crew_member/flight_assignments/FlightCrewMemberFlightAssignmentUpdateService.java
  src/main/java/acme/features/flight_crew_member/flight_assignments/UncompletedFlightAssignmentListService.java
  src/main/resources/WEB-INF/data/sample/flight-assignment.csv
  src/main/resources/WEB-INF/views/authenticated/flight-crew-member/form.jsp
  src/main/resources/WEB-INF/views/authenticated/flight-crew-member/messages-en.i18n
  src/main/resources/WEB-INF/views/authenticated/flight-crew-member/messages-es.i18n
  src/main/resources/WEB-INF/views/flight-crew-member/activity-log/form.jsp
  src/main/resources/WEB-INF/views/flight-crew-member/activity-log/list.jsp
  src/main/resources/WEB-INF/views/flight-crew-member/activity-log/messages-en.i18n
  src/main/resources/WEB-INF/views/flight-crew-member/activity-log/messages-es.i18n
  src/main/resources/WEB-INF/views/flight-crew-member/flight-assignment/form.jsp
  src/main/resources/WEB-INF/views/flight-crew-member/flight-assignment/list.jsp
  src/main/resources/WEB-INF/views/flight-crew-member/flight-assignment/messages-en.i18n
  src/main/resources/WEB-INF/views/flight-crew-member/flight-assignment/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: Student 3, D03, Mandatory

#206 feat(Airport administrator): Se ha completado las funcionalidades de gestion de aeropuertos por parte de un administrator.
  .classpath
  src/main/java/acme/entities/airport/Airport.java
  src/main/java/acme/features/administrator/airport/AdministratorAirportController.java
  src/main/java/acme/features/administrator/airport/AdministratorAirportCreateService.java
  src/main/java/acme/features/administrator/airport/AdministratorAirportListService.java
  src/main/java/acme/features/administrator/airport/AdministratorAirportRepository.java
  src/main/java/acme/features/administrator/airport/AdministratorAirportShowService.java
  src/main/java/acme/features/administrator/airport/AdministratorAirportUpdateService.java
  src/main/java/acme/features/manager/leg/ManagerLegCreateService.java
  src/main/resources/WEB-INF/data/sample/airport.csv
  src/main/resources/WEB-INF/views/administrator/airport/form.jsp
  src/main/resources/WEB-INF/views/administrator/airport/list.jsp
  src/main/resources/WEB-INF/views/administrator/airport/messages-en.i18n
  src/main/resources/WEB-INF/views/administrator/airport/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: D03, Mandatory, Groupal

#205 Student1 m08 & m09
  .project
  src/main/java/acme/components/ExchangeRate.java
  src/main/java/acme/constraints/LegValidator.java
  src/main/java/acme/entities/leg/Leg.java
  src/main/java/acme/features/manager/flight/ManagerFlightCreateService.java
  src/main/java/acme/features/manager/flight/ManagerFlightPublishService.java
  src/main/java/acme/features/manager/flight/ManagerFlightUpdateService.java
  src/main/java/acme/features/manager/leg/ManagerLegCancelledService.java
  src/main/java/acme/features/manager/leg/ManagerLegCreateService.java
  src/main/java/acme/features/manager/leg/ManagerLegDelayedService.java
  src/main/java/acme/features/manager/leg/ManagerLegDeleteService.java
  src/main/java/acme/features/manager/leg/ManagerLegLandedService.java
  src/main/java/acme/features/manager/leg/ManagerLegPublishService.java
  src/main/java/acme/features/manager/leg/ManagerLegRepository.java
  src/main/java/acme/features/manager/leg/ManagerLegShowService.java
  src/main/java/acme/features/manager/leg/ManagerLegUpdateService.java
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: Student 1, D03, Mandatory
