Repository DP2-IIS-C1048/Acme-ANS-D, pull requests merged in 2025-03, with the labels that each got.

#68 Añadida la entidad Aircraft
  src/main/java/acme/constraints/AircraftValidator.java
  src/main/java/acme/constraints/ValidAircraft.java
  src/main/java/acme/entities/aircraft/Aircraft.java
  src/main/java/acme/entities/aircraft/AircraftRepository.java
  src/main/java/acme/entities/aircraft/Status.java
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: D02, Mandatory, Groupal

#67 Añadido entidad ActivityLog
  src/main/java/acme/constraints/ActivityLogValidator.java
  src/main/java/acme/constraints/ValidActivityLog.java
  src/main/java/acme/entities/activity_log/ActivityLog.java
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: Student 3, D02, Mandatory

#75 Requisito Student1-M03 Manager
  reports/Student#1/~$ - Requirements - Student #1.docx
  src/main/java/acme/constraints/ManagerValidator.java
  src/main/java/acme/constraints/ValidManager.java
  src/main/java/acme/entities/airline_manager/AirlineManager.java
  src/main/java/acme/realms/manager/Manager.java
  src/main/java/acme/realms/manager/ManagerRepository.java
Labels: Student 1, D02, Mandatory

#52 Añadido el rol de FlightCrewMember
  src/main/java/acme/constraints/FlightCrewMemberValidator.java
  src/main/java/acme/constraints/ValidFlightCrewMember.java
  src/main/java/acme/realms/flight/crew/member/AvailabilityStatus.java
  src/main/java/acme/realms/flight/crew/member/FlightCrewMember.java
  src/main/java/acme/realms/flight/crew/member/FlightCrewMemberRepository.java
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: Student 3, D02, Mandatory

#57 Añadido la entidad FlightAssignment
  src/main/java/acme/entities/flight_assignment/CurrentStatus.java
  src/main/java/acme/entities/flight_assignment/Duty.java
  src/main/java/acme/entities/flight_assignment/FlightAssignment.java
Labels: Student 3, D02, Mandatory

#61 mandatory: added service
  src/main/java/acme/constraints/PromotionValidator.java
  src/main/java/acme/constraints/ValidPromotion.java
  src/main/java/acme/entities/service/Promotion.java
  src/main/java/acme/entities/service/PromotionRepository.java
  src/main/java/acme/entities/service/Service.java
Labels: D02, Mandatory, Groupal

#51 Passanger añadido
  src/main/java/acme/entities/passenger/Passenger.java
Labels: Student 2, D02, Mandatory

#54 Airport añadido
  src/main/java/acme/constraints/AirportValidator.java
  src/main/java/acme/constraints/ValidAirport.java
  src/main/java/acme/datatypes/OperationalScope.java
  src/main/java/acme/entities/airport/Airport.java
  src/main/java/acme/entities/airport/AirportRepository.java
Labels: D02, Mandatory, Groupal

#45 Customer añadido
  src/main/java/acme/constraints/CustomerValidator.java
  src/main/java/acme/constraints/ValidCustomer.java
  src/main/java/acme/entities/customer/Customer.java
  src/main/java/acme/entities/customer/CustomerRepository.java
Labels: Student 2, D02, Mandatory

#53 feat(Airline): Se ha añadido la entidad Airline.
  src/main/java/acme/constraints/AirlineValidator.java
  src/main/java/acme/constraints/ValidAirline.java
  src/main/java/acme/entities/airline/Airline.java
  src/main/java/acme/entities/airline/AirlineRepository.java
  src/main/java/acme/entities/airline/AirlineType.java
Labels: Student 4, D02, Mandatory

#56 mandatory: added maintenance_record entity
  src/main/java/acme/entities/maintenance/Involves.java
  src/main/java/acme/entities/maintenance/MaintenanceRecord.java
  src/main/java/acme/entities/maintenance/MaintenanceStatus.java
Labels: Student 5, D02, Mandatory

#55 mandatory: added technician entity
  src/main/java/acme/constraints/TechnicianValidator.java
  src/main/java/acme/constraints/ValidTechnician.java
  src/main/java/acme/realms/technician/Technician.java
  src/main/java/acme/realms/technician/TechnicianRepository.java
Labels: Student 5, D02, Mandatory

#48 Role AssitanceAgent editado:
  src/main/java/acme/realms/assistanceagent/AssistanceAgent.java
  src/main/java/acme/realms/assistanceagent/AssistanceAgentRepository.java
  src/main/java/constraints/AssistanceAgentValidator.java
  src/main/java/constraints/ValidAssistanceAgent.java
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: Student 4, D02, Mandatory

#145 Fix: added documents for D02
  reports/Group/00 - Requirements - Group.docx
  reports/Student#1/01 - Requirements - Student #1.docx
  reports/Student#2/02 - Requirements - Student #2.docx
  reports/Student#3/03 - Requirements - Student #3.docx
  reports/Student#4/04 - Requirements - Student #4.docx
  reports/Student#5/05 - Requirements - Student #5.docx
Labels: D02

#152 Updated student 5 constraints
  src/main/java/acme/entities/maintenance/MaintenanceRecord.java
  src/main/java/acme/entities/maintenance/Task.java
  src/main/java/acme/entities/service/Service.java
  src/main/java/acme/realms/technician/Technician.java
Labels: Student 5, D02

#157 Añadidos diagramas UML para Student 5
  reports/Student#5/uml_diagrams/student5ConstraintDiagram.uxf
  reports/Student#5/uml_diagrams/student5DatatypeDiagram.uxf
  reports/Student#5/uml_diagrams/student5EntityDiagram.uxf
  reports/Student#5/uml_diagrams/student5FormDiagram.uxf
  reports/Student#5/uml_diagrams/student5RealmDiagram.uxf
Labels: Student 5, D02, Supplementary 1

#156 Cambiadas restricciones de fullName y dateOfBirth
  src/main/java/acme/entities/passenger/Passenger.java
Labels: Student 2, D02, Revision

#155 Añadidas restricciones en atributos de la clase Booking
  src/main/java/acme/entities/booking/Booking.java
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: Student 2, D02, Revision

#153 Cambios en el validor de clase y en el atributo earnedPoints
  src/main/java/acme/constraints/CustomerValidator.java
  src/main/java/acme/realms/customer/Customer.java
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: Student 2, D02, Revision

#154 Creados datos iniciales del Student 2
  src/main/resources/WEB-INF/data/sample/airport.csv
  src/main/resources/WEB-INF/data/sample/booking.csv
  src/main/resources/WEB-INF/data/sample/bookingRecord.csv
  src/main/resources/WEB-INF/data/sample/customer.csv
  src/main/resources/WEB-INF/data/sample/passenger.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: Student 2, D02, Mandatory

#172 feat(Datos): Se han añadido datos para aircraft,flight,leg,manager,review
  .classpath
  .settings/org.eclipse.wst.common.component
  pom.xml
  src/main/java/acme/constraints/LegValidator.java
  src/main/java/acme/constraints/ManagerValidator.java
  src/main/java/acme/entities/flight/Flight.java
  src/main/java/acme/entities/leg/Leg.java
  src/main/java/acme/realms/manager/Manager.java
  src/main/resources/WEB-INF/data/sample/aircraft.csv
  src/main/resources/WEB-INF/data/sample/flight.csv
  src/main/resources/WEB-INF/data/sample/leg.csv
  src/main/resources/WEB-INF/data/sample/manager.csv
  src/main/resources/WEB-INF/data/sample/review.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: Student 1, D02, Mandatory

#60 mandatory: added sample data for technicians 1, 2, 3
  .settings/org.eclipse.wst.common.component
  src/main/resources/WEB-INF/data/sample/involves.csv
  src/main/resources/WEB-INF/data/sample/maintenance-record.csv
  src/main/resources/WEB-INF/data/sample/task.csv
  src/main/resources/WEB-INF/data/sample/technician.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: Student 5, D02, Mandatory

#150 Añadidos los datos de prueba para flightCrewMember
  src/main/java/acme/entities/aircraft/Aircraft.java
  src/main/java/acme/entities/aircraft/AircraftStatus.java
  src/main/java/acme/entities/airline/Airline.java
  src/main/java/acme/realms/flight_crew_member/FlightCrewMember.java
  src/main/resources/WEB-INF/data/sample/airline.csv
  src/main/resources/WEB-INF/data/sample/flight-assignment.csv
  src/main/resources/WEB-INF/data/sample/flight-crew-member.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: Student 3, D02, Mandatory
