Repository DP2-IIS-C1048/Acme-ANS-D, pull requests merged in 2025-05, with the labels that each got.

#198 Student2 m08
  .classpath
  .project
  .settings/org.eclipse.wst.common.component
  pom.xml
  src/main/java/acme/entities/booking/Booking.java
  src/main/java/acme/entities/booking/BookingRepository.java
  src/main/java/acme/entities/claim/Claim.java
  src/main/java/acme/entities/flight/Flight.java
  src/main/java/acme/entities/passenger/Passenger.java
  src/main/java/acme/features/customer/booking/CustomerBookingController.java
  src/main/java/acme/features/customer/booking/CustomerBookingCreateService.java
  src/main/java/acme/features/customer/booking/CustomerBookingListService.java
  src/main/java/acme/features/customer/booking/CustomerBookingPublishService.java
  src/main/java/acme/features/customer/booking/CustomerBookingRepository.java
  src/main/java/acme/features/customer/booking/CustomerBookingShowService.java
  src/main/java/acme/features/customer/booking/CustomerBookingUpdateService.java
  src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordController.java
  src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordCreateService.java
  src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordListService.java
  src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordRepository.java
  src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordShowService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerPublishService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerUpdateService.java
  src/main/java/acme/features/manager/flight/ManagerFlightController.java
  src/main/java/acme/realms/customer/CustomerRepository.java
  src/main/resources/WEB-INF/data/sample/airline.csv
  src/main/resources/WEB-INF/data/sample/airport.csv
  src/main/resources/WEB-INF/data/sample/passenger.csv
  src/main/resources/WEB-INF/views/customer/booking-record/form.jsp
  src/main/resources/WEB-INF/views/customer/booking-record/list.jsp
  src/main/resources/WEB-INF/views/customer/booking-record/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/booking-record/messasges-es.i18n
  src/main/resources/WEB-INF/views/customer/booking/form.jsp
  src/main/resources/WEB-INF/views/customer/booking/list.jsp
  src/main/resources/WEB-INF/views/customer/booking/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/booking/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: Student 2, D03, Mandatory

#214 Student2 S15
  src/main/java/acme/components/CurrencyExchange.java
  src/main/java/acme/features/customer/dashboard/CustomerDashboardRepository.java
  src/main/java/acme/forms/customer/CustomerDashboard.java
  src/main/resources/WEB-INF/data/sample/currency-exchange.csv
Labels: Student 2, D02, Supplementary 1

#228 Group5 m14
  src/main/java/acme/components/ServiceAdvisor.java
  src/main/java/acme/components/ServiceRepository.java
  src/main/java/acme/entities/service/Promotion.java
  src/main/java/acme/entities/service/Service.java
  src/main/resources/WEB-INF/data/sample/promotion.csv
  src/main/resources/WEB-INF/data/sample/service.csv
  src/main/resources/WEB-INF/views/fragments/footer.jsp
Labels: D03, Mandatory, Groupal

#204 Operaciones de administradores en aircrafts
  src/main/java/acme/features/adminstrator/aircraft/AdministratorAircraftController.java
  src/main/java/acme/features/adminstrator/aircraft/AdministratorAircraftCreateService.java
  src/main/java/acme/features/adminstrator/aircraft/AdministratorAircraftDisableService.java
  src/main/java/acme/features/adminstrator/aircraft/AdministratorAircraftListService.java
  src/main/java/acme/features/adminstrator/aircraft/AdministratorAircraftRepository.java
  src/main/java/acme/features/adminstrator/aircraft/AdministratorAircraftShowService.java
  src/main/java/acme/features/adminstrator/aircraft/AdministratorAircraftUpdateService.java
  src/main/resources/WEB-INF/views/administrator/aircraft/form.jsp
  src/main/resources/WEB-INF/views/administrator/aircraft/list.jsp
  src/main/resources/WEB-INF/views/administrator/aircraft/messages-en.i18n
  src/main/resources/WEB-INF/views/administrator/aircraft/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: D03, Mandatory, Groupal

#221 Student5 m08 & m09
  .classpath
  .settings/org.eclipse.wst.common.component
  src/main/java/acme/entities/maintenance/MaintenanceRecord.java
  src/main/java/acme/features/technician/involves/TechnicianInvolvesController.java
  src/main/java/acme/features/technician/involves/TechnicianInvolvesCreateService.java
  src/main/java/acme/features/technician/involves/TechnicianInvolvesDeleteService.java
  src/main/java/acme/features/technician/involves/TechnicianInvolvesListService.java
  src/main/java/acme/features/technician/involves/TechnicianInvolvesRepository.java
  src/main/java/acme/features/technician/involves/TechnicianInvolvesShowService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordController.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordCreateService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordDeleteService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordListAllPublishedService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordListService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordPublishService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordRepository.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordShowService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordUpdateService.java
  src/main/java/acme/features/technician/task/TechnicianTaskController.java
  src/main/java/acme/features/technician/task/TechnicianTaskCreateService.java
  src/main/java/acme/features/technician/task/TechnicianTaskDeleteService.java
  src/main/java/acme/features/technician/task/TechnicianTaskListAllPublishedService.java
  src/main/java/acme/features/technician/task/TechnicianTaskListService.java
  src/main/java/acme/features/technician/task/TechnicianTaskPublishService.java
  src/main/java/acme/features/technician/task/TechnicianTaskRepository.java
  src/main/java/acme/features/technician/task/TechnicianTaskShowService.java
  src/main/java/acme/features/technician/task/TechnicianTaskUpdateService.java
  src/main/resources/WEB-INF/data/sample/involves.csv
  src/main/resources/WEB-INF/data/sample/maintenance-record.csv
  src/main/resources/WEB-INF/data/sample/task.csv
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/technician/involves/form.jsp
  src/main/resources/WEB-INF/views/technician/involves/list.jsp
  src/main/resources/WEB-INF/views/technician/involves/messages-en.i18n
  src/main/resources/WEB-INF/views/technician/involves/messages-es.i18n
  src/main/resources/WEB-INF/views/technician/maintenance-record/form.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record/list.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record/messages-en.i18n
  src/main/resources/WEB-INF/views/technician/maintenance-record/messages-es.i18n
  src/main/resources/WEB-INF/views/technician/task/form.jsp
  src/main/resources/WEB-INF/views/technician/task/list.jsp
  src/main/resources/WEB-INF/views/technician/task/messages-en.i18n
  src/main/resources/WEB-INF/views/technician/task/messages-es.i18n
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: Student 5, D03, Mandatory

#239 Actualizar perfil de Customer implementado
  src/main/java/acme/constraints/CustomerValidator.java
  src/main/java/acme/features/authenticated/customer/AuthenticatedCustomerController.java
  src/main/java/acme/features/authenticated/customer/AuthenticatedCustomerRepository.java
  src/main/java/acme/features/authenticated/customer/AuthenticatedCustomerUpdateService.java
  src/main/resources/WEB-INF/views/authenticated/customer/form.jsp
  src/main/resources/WEB-INF/views/authenticated/customer/messages-en.i18n
  src/main/resources/WEB-INF/views/authenticated/customer/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: Student 2, D03, Supplementary 1

#237 Operaciones de administrators en Booking Completada
  src/main/java/acme/features/administrator/booking/AdministratorBookingController.java
  src/main/java/acme/features/administrator/booking/AdministratorBookingListService.java
  src/main/java/acme/features/administrator/booking/AdministratorBookingRepository.java
  src/main/java/acme/features/administrator/booking/AdministratorBookingShowService.java
  src/main/java/acme/features/administrator/bookingRecord/AdminisitratorBookingRecordShowService.java
  src/main/java/acme/features/administrator/bookingRecord/AdministratorBookingRecordController.java
  src/main/java/acme/features/administrator/bookingRecord/AdministratorBookingRecordListService.java
  src/main/java/acme/features/administrator/bookingRecord/AdministratorBookingRecordRepository.java
  src/main/resources/WEB-INF/views/administrator/booking-record/form.jsp
  src/main/resources/WEB-INF/views/administrator/booking-record/list.jsp
  src/main/resources/WEB-INF/views/administrator/booking-record/messages-en.i18n
  src/main/resources/WEB-INF/views/administrator/booking-record/messasges-es.i18n
  src/main/resources/WEB-INF/views/administrator/booking/form.jsp
  src/main/resources/WEB-INF/views/administrator/booking/list.jsp
  src/main/resources/WEB-INF/views/administrator/booking/messages-en.i18n
  src/main/resources/WEB-INF/views/administrator/booking/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: Student 2, D03, Supplementary 1

#267 Añadido testing report del Student1
  reports/Student#1/Testing-report.docx
Labels: Student 1, D04, Mandatory

#266 Testing de Student2
  src/main/java/acme/features/customer/booking/CustomerBookingCreateService.java
  src/main/java/acme/features/customer/booking/CustomerBookingPublishService.java
  src/main/java/acme/features/customer/booking/CustomerBookingRepository.java
  src/main/java/acme/features/customer/booking/CustomerBookingShowService.java
  src/main/java/acme/features/customer/booking/CustomerBookingUpdateService.java
  src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordCreateService.java
  src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordListService.java
  src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordRepository.java
  src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordShowService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerPublishService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerShowService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerUpdateService.java
  src/main/resources/WEB-INF/views/customer/booking-record/form.jsp
  src/main/resources/WEB-INF/views/customer/booking-record/list.jsp
  src/main/resources/WEB-INF/views/customer/booking-record/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/booking-record/messasges-es.i18n
  src/main/resources/WEB-INF/views/customer/booking/form.jsp
  src/main/resources/WEB-INF/views/customer/booking/list.jsp
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
  src/test/resources/customer/booking/create.hack
  src/test/resources/customer/booking/create.safe
  src/test/resources/customer/booking/list-mine.safe
  src/test/resources/customer/booking/list.hack
  src/test/resources/customer/booking/publish-mine.safe
  src/test/resources/customer/booking/publish-not-mine.hack
  src/test/resources/customer/booking/show-mine.safe
  src/test/resources/customer/booking/show-not-mine.hack
  src/test/resources/customer/booking/update-mine.safe
  src/test/resources/customer/booking/update.hack
  src/test/resources/customer/bookingRecord/create.hack
  src/test/resources/customer/bookingRecord/create.safe
  src/test/resources/customer/bookingRecord/list-mine.safe
  src/test/resources/customer/bookingRecord/list-not-mine.hack
  src/test/resources/customer/bookingRecord/show-mine.safe
  src/test/resources/customer/bookingRecord/show-not-mine.hack
  src/test/resources/customer/passenger/create.safe
  src/test/resources/customer/passenger/list-mine.safe
  src/test/resources/customer/passenger/list-not-mine.hack
  src/test/resources/customer/passenger/publish-mine.safe
  src/test/resources/customer/passenger/publish-not-mine.hack
  src/test/resources/customer/passenger/show-mine.safe
  src/test/resources/customer/passenger/show-not-mine.hack
  src/test/resources/customer/passenger/update-mine.safe
  src/test/resources/customer/passenger/update-not-mine.hack
Labels: Student 2, D04, Mandatory

#265 Añadido testing report Student2
  reports/Student#2/Testing Report.docx
Labels: Student 2, D04, Mandatory

#271 Group1 m17
  src/main/java/acme/constraints/AirportValidator.java
  src/main/java/acme/features/administrator/airline/AdministratorAirlineShowService.java
  src/main/java/acme/features/administrator/airline/AdministratorAirlineUpdateService.java
  src/main/java/acme/features/administrator/airport/AdministratorAirportUpdateService.java
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
  src/test/resources/administrator/airport/airport-create.safe
  src/test/resources/administrator/airport/list.safe
  src/test/resources/administrator/airport/show.hack
  src/test/resources/administrator/airport/show.safe
  src/test/resources/administrator/airport/update-mine.safe
  src/test/resources/administrator/airport/update.hack
Labels: D04, Mandatory, Groupal

#270 Test Suite anda Testing report
  reports/Student#4/Testing Report - Student #4.docx
  src/test/resources/assistanceAgent/claim/claim-create.hack
  src/test/resources/assistanceAgent/claim/claim-create.safe
  src/test/resources/assistanceAgent/claim/claim-delete.hack
  src/test/resources/assistanceAgent/claim/claim-delete.safe
  src/test/resources/assistanceAgent/claim/claim-publish.hack
  src/test/resources/assistanceAgent/claim/claim-publish.safe
  src/test/resources/assistanceAgent/claim/claim-show.hack
  src/test/resources/assistanceAgent/claim/claim-show.safe
  src/test/resources/assistanceAgent/claim/claim-update.hack
  src/test/resources/assistanceAgent/claim/claim-update.safe
  src/test/resources/assistanceAgent/claim/completed-claim-list.hack
  src/test/resources/assistanceAgent/claim/completed-claim-list.safe
  src/test/resources/assistanceAgent/claim/pending-claim-list.hack
  src/test/resources/assistanceAgent/claim/pending-claim-list.safe
  src/test/resources/assistanceAgent/trackingLog/trackingLog-create.hack
  src/test/resources/assistanceAgent/trackingLog/trackingLog-create.safe
  src/test/resources/assistanceAgent/trackingLog/trackingLog-delete.safe
  src/test/resources/assistanceAgent/trackingLog/trackingLog-list.hack
  src/test/resources/assistanceAgent/trackingLog/trackingLog-list.safe
  src/test/resources/assistanceAgent/trackingLog/trackingLog-publish.hack
  src/test/resources/assistanceAgent/trackingLog/trackingLog-publish.safe
  src/test/resources/assistanceAgent/trackingLog/trackingLog-show.hack
  src/test/resources/assistanceAgent/trackingLog/trackingLog-show.safe
  src/test/resources/assistanceAgent/trackingLog/trackingLog-update.hack
  src/test/resources/assistanceAgent/trackingLog/trackingLog-update.safe
Labels: Student 4, D04, Mandatory
